id: 615d974d-3252-4950-b320-0ebf8d585622
name: Identity Service - Prod
values:
  - key: baseUrl
    value: 'http://identity-api.identity.svc.cluster.local:3001'
    enabled: true
    type: default
_postman_variable_scope: environment
color: 0
_postman_exported_at: '2026-02-17T22:29:00.193Z'
_postman_exported_using: Postman/11.0.0
